AWSTemplateFormatVersion: "2010-09-09"
Description: Notification Service Stack

Parameters:
  DeploymentBucket:
    Type: String
  S3Key:
    Type: String
    
  KinghostApiToken:
    Type: String
    NoEcho: true
  KinghostApiUser:
    Type: String
  KinghostSmtpUser:
    Type: String
  KinghostSmtpPass:
    Type: String
    NoEcho: true

Resources:

  NotificationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: medsafe-notification-service
      Handler: dist/lambda.handler
      Runtime: nodejs20.x
      Role: arn:aws:iam::326993352985:role/MedSafe-NotificationService
      Timeout: 20

      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref S3Key

      Environment:
        Variables:
          NODE_ENV: production
          DYNAMO_TABLE_NAME: MedSafe-Events
          KINGHOST_API_BASE_URL: https://api.smtplw.com.br/v1/messages
          KINGHOST_API_TOKEN: !Ref KinghostApiToken
          KINGHOST_API_USER: !Ref KinghostApiUser
          KINGHOST_SMTP_HOST: kinghost.smtpkl.com.br
          KINGHOST_SMTP_PORT: "587"
          KINGHOST_SMTP_USER: !Ref KinghostSmtpUser
          KINGHOST_SMTP_PASS: !Ref KinghostSmtpPass
          KINGHOST_SMTP_FROM: "Medsafe <medsafe@medsafe.goncdev.com.br>"
          SQS_QUEUE_URL: https://sqs.sa-east-1.amazonaws.com/326993352985/medsafe-auth-to-notification
          SQS_QUEUE_NAME: medsafe-auth-to-notification

  NotificationSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: arn:aws:sqs:sa-east-1:326993352985:medsafe-auth-to-notification
      FunctionName: !Ref NotificationLambda
      BatchSize: 10
      Enabled: true
